version: '3.9'

services:
  cebta-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cebta-mcp-demo
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - APP_BASE_URL=http://localhost:8000
    restart: unless-stopped
